export const CITY_WEATHER_FETCHED = 'CITY_WEATHER_FETCHED';
export const CITIES_FETCHED = 'CITIES_FETCHED';
export const SELECTED_CITY_ADDED = 'SELECTED_CITY_ADDED';
export const SELECTED_CITY_REMOVED = 'SELECTED_CITY_REMOVED';
